# Generated by Django 3.2.14 on 2022-09-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
